### ISSUE TITLE
What is the difference?

### ISSUE THREAD

**Issue by hyf6661669** [chipsalliance/Cores-SweRV#1]
What is the difference between  https://github.com/chipsalliance/Cores-SweRV and https://github.com/westerndigitalcorporation/swerv_eh1. Are they maintained by the same people?

**Comment by jrahmeh** [comment]
No difference.  The "westerndigitalcorporation" repository will be maintained for a while as a courtesy to our early users/adopters.  We encourage all users to move to the "chipalliance" repository.
