### ISSUE TITLE
Try running multi thread program on swerv EH1 core

### ISSUE THREAD

**Issue by rajat-agnisys** [chipsalliance/Cores-SweRV#103]
Hello,

I am trying to run multi thread program on EH1 core but facing some assertion fail in core RTL. 
Is EH1 supports multi thread programming?

Thanks
Rajat

**Comment by aprnath** [comment]
EH1 implements only a single hardware thread. EH2 supports two hardware threads.

**Comment by rajat-agnisys** [comment]
Thanks, 
I will try with EH2
