### ISSUE TITLE
Repo renaming

### ISSUE THREAD

**Issue by olofk** [chipsalliance/Cores-SweRV#115]
I just noticed that the SweRV repos were renamed to VeeR. Could we pleeeeeease take the opportunity to not just change from SweRV to VeeR, but also call them VeeR-EH1, VeeR-EL2 and VeeR-EH2 for consistency?

I will also make sure to rename SweRVolf to.... VeeRwolf?

**Comment by mgielda** [comment]
Added EH1, for consistency. Good suggestion, thanks! Closing.

**Comment by mgielda** [comment]
yeah, I think VeeRwolf sounds kinda cool ;-)
