### ISSUE TITLE
Testbench does not verilate

### ISSUE THREAD

**Issue by toddstrader** [chipsalliance/Cores-SweRV#13]
The Verilator external test suite is breaking on the SweRV test, and this time I don't believe it is a Verilator regression:
https://travis-ci.com/verilator/verilator_ext_tests/jobs/228899219

It appears that commit `0dacc978` moved `finished` outside of a macro block that was probably there to get around this issue in the first place.  Now Verilator complains that it is defined twice.

**Comment by aprnath** [comment]
Thanks for reporting this, Todd.
I have pushed a patch for this # fc331027c

**Comment by toddstrader** [comment]
Confirmed, thanks:
https://travis-ci.com/verilator/verilator_ext_tests/builds/125826326?utm_medium=notification&utm_source=email
