### ISSUE TITLE
Boot code from iccm

### ISSUE THREAD

**Issue by milk0920** [chipsalliance/Cores-SweRV#15]
Hi , if we want to use the iccm ，Can I simply edit the link file， And let the cpu core to automatically download the code from external rom/ram/flash, is that possible, if we do not have the dma master design, but we still want to run code in iccm

**Comment by agrobman** [comment]
provided TB doesn't support any usage of ICCM

**Comment by agrobman** [comment]
checkout latest and *_iccm test ...

**Comment by aprnath** [comment]
Closing this. Please see prior comment about using the *iccm tests. It enables one of 

- a gasket that allows stores to ICCM by hooking up the LSU to the DMA port
- or a testbench preload of the ICCM

Thanks
