### ISSUE TITLE
Initialization/startup sequence and linker script for large C programs

### ISSUE THREAD

**Issue by dareyouspam** [chipsalliance/Cores-SweRV#18]
Hello - I am trying to run simulations of some large C programs on the SweRV RTL, but figuring out the expected initialization and finish functions, linker script and any other system configuration requirements is proving to me difficult for me - exec.log shows the simulation takes an exception in the third instruction and keeps looping there. Could you please add a compilation recipe for some arbitrarily large C programs that would run on the default SweRV configuration? Thanks in advance.

**Comment by aprnath** [comment]
Coming shortly..
