### ISSUE TITLE
Code cleanup: fix line endings

### ISSUE THREAD

**Issue by ChippendaleMupp** [chipsalliance/Cores-SweRV#2]
Perforce is complaining about line endings in the 4 files below.  dos2unix seems to clean them up. (Command for recursive cleanup:  'find . -type f -print0 | xargs -0 dos2unix'

- design/dmi/dmi_wrapper.v
- design/dmi/dmi_jtag_to_core_sync.v
- testbench/hex/data.hex
- testbench/hex/program.hex

**Comment by jrahmeh** [comment]
Fixed.
