### ISSUE TITLE
Code cleanup: replace spurious tabs with spaces

### ISSUE THREAD

**Issue by ChippendaleMupp** [chipsalliance/Cores-SweRV#3]
Lots of files use both tabs and spaces to indent.  If you don't have the same tab setting as the last engineer who touched the code then the indenting breaks.  Can we replace the tabs with spaces?

It looks like 4 spaces is what is used for the file's I've looked at.

Here's an example code segment taken at random:

![image](https://user-images.githubusercontent.com/662745/60980581-a2661b80-a32c-11e9-8b88-d41fff2a8ce8.png)

**Comment by jrahmeh** [comment]
Fixed in version 1.2
