### ISSUE TITLE
RV core With AHB bus will cause bug when send read operation

### ISSUE THREAD

**Issue by walkingjian** [chipsalliance/Cores-SweRV#31]
In the latest test, RV core in my soc envirent will cause NMI err.

The detail is because the RV core send a 64bit width read transation of AHB bus, while I only wirte an "unsigned int read regitster" code in my c file.
And ,the register I want read is right the last register of one module, so this 64 bit read cause slverr back, and then the RV core get into MNI interrupt.

**Comment by aprnath** [comment]
Hi,
Please use MRAC to set the region for your device to be non-idempotent. Non-idempotent (or side-effect) regions will support exact size for load stores, and is recommended for non-memory load stores, especially to devices.
