### ISSUE TITLE
EH2 and EL2 are missing.

### ISSUE THREAD

**Issue by pieter3d** [chipsalliance/Cores-SweRV#32]
Earlier this month Western Digital announced two new cores, EH2 and EL2, in addition to the current one here, EH1: https://www.westerndigital.com/risc-v

But I don't see them in this repository, linked on that page. Where could I find these two new cores?

**Comment by aprnath** [comment]
EH2/EL2 are visible to ChipsAlliance members for now and will be globally visibly at some later date.
