### ISSUE TITLE
SWERV CPU doesn't work properly if memory interface HREADY signal is high by default

### ISSUE THREAD

**Issue by vit82** [chipsalliance/Cores-SweRV#46]
SWERV CPU doesn't work properly if memory interface HREADY signal (highlighted on the waveform) is high by default:
![image](https://user-images.githubusercontent.com/55279763/75802436-59fce180-5d85-11ea-83df-0cda047dd2f6.png)

If HREADY is low as shown below, the CPU work fine.
![image](https://user-images.githubusercontent.com/55279763/75802628-ae07c600-5d85-11ea-9533-40a86e7b0bc8.png)

**Comment by vit82** [comment]
In this case HREADY comes from the memory where proram executable code locates (ROM).
In my opinion according to AMBA standard HREADY is permitted to be high by default. 
Please, comment.

**Comment by aprnath** [comment]
Hi, 
Please clarify a few things in your report for us:

- What are the two waveforms provided? Is the 2nd one the "working" case, and the 1st one the failing case?
- Are both cases using the same slave IP?
- We would like to understand how the master and slave are connected. Is there a bridge or interconnect logic between them? A diagram or tb_top verilg would be useful.
- In the failing case we don't see hrdata @rvtop being drive the cycle after transaction starts and hready is still high. If hready is high, the DUT expects data that cycle.

Thanks

**Comment by agrobman** [comment]
If the 1st diagram is your failing case, seems that your slave drives zero data for the CPU request of 0x80000000 -( the hready is asserted for next clock after HTRANS=2) if your slave needs more time it should drop hready right after transaction start .

**Comment by vit82** [comment]
Thank you. Indeed between SWERV CPU and ROM, there's AHB switch fabric which doesn't work fine with AHB-lite provided by SWERV CPU. 
That was the main root cause of the problems.
