### ISSUE TITLE
access dccm through dma port

### ISSUE THREAD

**Issue by qq27303272** [chipsalliance/Cores-SweRV#53]
When use external dma master to read/write data from/to DCCM through dma port, it's need more cycles (up to 20 cycles if config AHB-lite bus),  why need so many cycles to access?  if there are some ways to speed up this operation?    

thanks!

**Comment by agrobman** [comment]
DMA port arbitrates with CPU over DCCM. CPU has priority over DMA. MFDC register provides some control for DMA/Core priority settings.
