### ISSUE TITLE
question regarding  how to run own C code on the core

### ISSUE THREAD

**Issue by mikemusasa** [chipsalliance/Cores-SweRV#58]
Hi, 
I have managed to perform all of the steps of the read me document and test the hello World. 
I was wondering on what is the correct way to run my own written c program on the SweRV core ? 

i wrote a simple c code called testar that is suppose to print out a simple text " the test worked " . 
I put my C code in  testbench/ asm .
I tried the command make -f $RV_ROOT/tools/Makefile program.hex TEST=testar  

 is this the right way to go abou it , even for big C codes  ?

**Comment by agrobman** [comment]
there are a few things you need to consider :
1) provided Makefile builds executable from a single source : to build multi-source  program you need to write the build recipe in the <test_name>.makefile, which in the end creates program.hex and data.hex files
2) to run C program, you need to have crt0 or boot code written in assembler which initializes CPU, sets up stack pointer, calls "main" function and terminates simulation. You can review hello_world.s test how to initialize the CPU and terminate simulation and also cmark.c how to add this assembly boot code to a C source.
3) Address map of the CPU/TB - DCCM/ICCM addresses/sizes, Reset Vector, set to 0. Review provided linker command files.
4) the TB memory Data and Program slaves have limited capacity of 64KB each (this can be changed with a parameter value ...
5) the TB memories ignore upper address lines, appearing to the CPU as repeating the same content every 64KB;
6) program.hex and data.hex files should have( @) addresses below 0x10000  to be loaded to the TB memories, any code/data with addresses higher then 0x10000 will be ignored by TB
7) CPU has separate busses for instruction fetches and data accesses, which connected to different TB memories. You may place program code starting from address 0, and data/constants from address 0x10000, but you have to build data.hex file to have addresses below 0x10000. See Makefile for some technics how to do this.
8) to use DCCM see *_dccm.* linker control file - this is a bit tricky. (DCCM need to be preloaded/initialized before use)
