### ISSUE TITLE
Which signal should I choose to trace Load/Store/pipeline state

### ISSUE THREAD

**Issue by ymlei** [chipsalliance/Cores-SweRV#67]
Hi! I want to trace memory accesses and their target address during the program running on SweRV Core. Which signal should I trace? How about coming to the pipeline state(stall, bypass...)?

**Comment by deepakpan** [comment]
Which signals specifically you are looking it? Do you want to look at the DCCM access signals in the waves or through the trace port. Please provide more details and I will try to provide the answer.
