### ISSUE TITLE
typo in swerv.config

### ISSUE THREAD

**Issue by sobuch** [chipsalliance/Cores-SweRV#70]
In https://github.com/chipsalliance/Cores-SweRV/blob/master/configs/swerv.config#L1914
```
 $jh{memmap}{cosnoleio} = $config{memmap}{serialio} if exists $config{memmap}{serialio};
```
I suppose it should be: cosnoleio -> consoleio

**Comment by aprnath** [comment]
Thanks for reporting. Note that this is only used by the testbench, and not the design itself. 
Will be fixed in next release.

**Comment by sobuch** [comment]
I see this changed in the new version, however it still doesn't work for me.

Currently, there is the following at https://github.com/chipsalliance/Cores-SweRV/blob/master/configs/swerv.config#L1962:
```
    foreach my $tag (qw ( size page_size serialio )) {
        $jh{memmap}{tag} = $config{memmap}{ta} if exists $config{memmap}{tag};
    }
```
Could it be more like this?
```
    $config{memmap}{consoleio} = $config{memmap}{serialio} if exists $config{memmap}{serialio};

    foreach my $tag (qw ( size page_size serialio consoleio)) {
        $jh{memmap}{$tag} = $config{memmap}{$tag} if exists $config{memmap}{$tag};
    }
```

**Comment by aprnath** [comment]
Indeed. Good catch Sam.

**Comment by sobuch** [comment]
I can confirm its fine now, thus closing this issue. Thank you for looking into this.
