### ISSUE TITLE
Can I integrate the Cores-SweRV on Zedboard fpga?

### ISSUE THREAD

**Issue by kingstone1927** [chipsalliance/Cores-SweRV#80]
I have a Zedboard fpga and want to integrate this Core into it. Can I do that with this repository? What are the detailed step-by-step on how to do it? I would be really appreciate if someone could help me. 
Thanks

Thach Nguyen

**Comment by aprnath** [comment]
Closing this. Please look at https://github.com/chipsalliance/Cores-SweRVolf or https://github.com/chipsalliance/Cores-SweRV_fpga for hints on how to use this core in fpga systems.
