### ISSUE TITLE
print instruction to exec.log

### ISSUE THREAD

**Issue by kingstone1927** [chipsalliance/Cores-SweRV#87]
Is there a way for me to print RISC-V instructions along with clock cycle into exec.log?

Thanks in advance.

**Comment by agrobman** [comment]
it does - first number in the exec.log  is the clock cycle, then executed instruction number and hart ID (0), then instruction address and then opcode. Using <test>.dis you can find mnemonics

You can also try incorporate dasm.svi from EL2 DB to print mnemonics in exec.log

**Comment by kingstone1927** [comment]
@agrobman  Thank you!
I assume that exec.log from EL2 will contain the mnemonics after running the simulation, does it?
