### ISSUE TITLE
which unit control flushing of the pipelines?

### ISSUE THREAD

**Issue by kingstone1927** [chipsalliance/Cores-SweRV#88]
Hello everyone,

I wonder which unit/code sections that control the flushing of the pipelines at the decode stage. 

Thank you!

**Comment by agrobman** [comment]
TLU initiates pipe flush, but not in decode stage ..

**Comment by kingstone1927** [comment]
@agrobman  Can you help me pointing out code sections that initiate pipe flush? 

As I understand, flush is resetting the pipelines/registers to zero values. I wonder if that is a correct way to understand flush. If so,  I am trying to find out which code sections defining the register pipelines and which code sections triggering the reset of the register pipelines. 
Please correct me if I am wrong in understanding flush. I really appreciate it if you can help me with this.

Thanks in advance.

**Comment by aprnath** [comment]
I left a comment in #90
