### ISSUE TITLE
No tags for releases

### ISSUE THREAD

**Issue by robtaylor** [chipsalliance/Cores-SweRV#91]
This makes it very hard to track what is considered aa released version!

**Comment by agrobman** [comment]
each release has a branch named as branch-1.X .. 
master branch is latest release

**Comment by robtaylor** [comment]
I'm afraid that that doesn't help me know what the release is exactly. Also only a small number of versions have a branch.

I would suggest a standard software-style release process of bumping the version in the .core file, readme, etc, and then tagging that point with v<version number>

**Comment by aprnath** [comment]
@robtaylor, actually all official releases (1.0 - 1.8) do have a branch. However your point is also valid regarding tag usage. We will  look into this - maybe even consult with a person versed in "software-style" :-)

Thanks for the suggestion.

**Comment by jrahmeh** [comment]
Added tags v1.5, v1.6, v1.7, and v1.8

**Comment by robtaylor** [comment]
Amazing! Thank you Ajay and jrahmeh
